
generate-spec:
    `which pypy3 || which python3` ./gen_spec.py spec.json

watch:
    watchexec -e py -c -- just generate-spec

download-html-spec:
    wget https://registry.khronos.org/OpenGL/specs/gl/GLSLangSpec.4.60.html
