name: "Release Artifacts"
on:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write
jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.14.1
      - name: Build
        run: ./release.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            zig-out/archives/*
          
